vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       timetable:
           uri_prefix: /images/timetable
           upload_destination: '%kernel.project_dir%/public/images/timetable'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
